### ISSUE TITLE
EAreport library package issue

### ISSUE THREAD

**Issue by wli7** [interactivereport/RNASequest#32]
I got errors for no package called bookdown, kableExtra.

I tried to install the packages in R in the conda environment. I could install bookdown but I got error for KableExtra during installation.
<img width="1331" alt="KableExtra_error" src="https://user-images.githubusercontent.com/72885412/163454702-3ac6cb5c-c495-4ad9-b76b-6d77b2b9d936.png">

**Comment by sunyumail93** [comment]
The bookdown and kableExtra have been added to the env yml file (https://github.com/interactivereport/RNASequest/blob/main/install.yml). Could you try to build a new env using it?

**Comment by wli7** [comment]
Sure, Let me try it. Thanks.

**Comment by z5ouyang** [comment]
Please reopen if issue still exists.
